// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

[assembly: DateTimeConstants("WInterop.Tests.SourceGenerators")]

namespace WInterop.Tests.SourceGenerators;

public class DateTimeConstantsTests
{
    [Fact]
    public void BasicFunctionality()
    {
        AutoGeneratedConstants.Integers.CurrentYear.Should().BeGreaterThan(2020);
        AutoGeneratedConstants.Strings.CurrentTwoDigitHour.Length.Should().Be(2);
    }
}
