// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using WInterop.Gdi;

namespace WInterop.GdiPlus.EmfPlus;

public enum RecordType : uint
{
    EmfHeader = MetafileRecordType.Header,
    EmfPolyBezier = MetafileRecordType.PolyBezier,
    EmfPolygon = MetafileRecordType.Polygon,
    EmfPolyline = MetafileRecordType.Polyline,
    EmfPolyBezierTo = MetafileRecordType.PolyBezierTo,
    EmfPolylineTo = MetafileRecordType.PolylineTo,
    EmfPolyPolyline = MetafileRecordType.PolyPolyline,
    EmfPolyPolygon = MetafileRecordType.PolyPolygon,
    EmfSetWindowExtEx = MetafileRecordType.SetWindowExtEx,
    EmfSetWindowOrgEx = MetafileRecordType.SetWindowOrgEx,
    EmfSetViewportExtEx = MetafileRecordType.SetViewportExtEx,
    EmfSetViewportOrgEx = MetafileRecordType.SetViewportOrgEx,
    EmfSetBrushOrgEx = MetafileRecordType.SetBrushOrgEx,
    EmfEof = MetafileRecordType.Eof,
    EmfSetPixelV = MetafileRecordType.SetPixelV,
    EmfSetMapperFlags = MetafileRecordType.SetMapperFlags,
    EmfSetMapMode = MetafileRecordType.SetMapMode,
    EmfSetBkMode = MetafileRecordType.SetBkMode,
    EmfSetPolyFillMode = MetafileRecordType.SetPolyFillMode,
    EmfSetROP2 = MetafileRecordType.SetROP2,
    EmfSetStretchBltMode = MetafileRecordType.SetStretchBltMode,
    EmfSetTextAlign = MetafileRecordType.SetTextAlign,
    EmfSetColorAdjustment = MetafileRecordType.SetColorAdjustment,
    EmfSetTextColor = MetafileRecordType.SetTextColor,
    EmfSetBkColor = MetafileRecordType.SetBkColor,
    EmfOffsetClipRgn = MetafileRecordType.OffsetClipRgn,
    EmfMoveToEx = MetafileRecordType.MoveToEx,
    EmfSetMetaRgn = MetafileRecordType.SetMetaRgn,
    EmfExcludeClipRect = MetafileRecordType.ExcludeClipRect,
    EmfIntersectClipRect = MetafileRecordType.IntersectClipRect,
    EmfScaleViewportExtEx = MetafileRecordType.ScaleViewportExtEx,
    EmfScaleWindowExtEx = MetafileRecordType.ScaleWindowExtEx,
    EmfSaveDC = MetafileRecordType.SaveDC,
    EmfRestoreDC = MetafileRecordType.RestoreDC,
    EmfSetWorldTransform = MetafileRecordType.SetWorldTransform,
    EmfModifyWorldTransform = MetafileRecordType.ModifyWorldTransform,
    EmfSelectObject = MetafileRecordType.SelectObject,
    EmfCreatePen = MetafileRecordType.CreatePen,
    EmfCreateBrushIndirect = MetafileRecordType.CreateBrushIndirect,
    EmfDeleteObject = MetafileRecordType.DeleteObject,
    EmfAngleArc = MetafileRecordType.AngleArc,
    EmfEllipse = MetafileRecordType.Ellipse,
    EmfRectangle = MetafileRecordType.Rectangle,
    EmfRoundRect = MetafileRecordType.RoundRect,
    EmfArc = MetafileRecordType.Arc,
    EmfChord = MetafileRecordType.Chord,
    EmfPie = MetafileRecordType.Pie,
    EmfSelectPalette = MetafileRecordType.SelectPalette,
    EmfCreatePalette = MetafileRecordType.CreatePalette,
    EmfSetPaletteEntries = MetafileRecordType.SetPaletteEntries,
    EmfResizePalette = MetafileRecordType.ResizePalette,
    EmfRealizePalette = MetafileRecordType.RealizePalette,
    EmfExtFloodFill = MetafileRecordType.ExtFloodFill,
    EmfLineTo = MetafileRecordType.LineTo,
    EmfArcTo = MetafileRecordType.ArcTo,
    EmfPolyDraw = MetafileRecordType.PolyDraw,
    EmfSetArcDirection = MetafileRecordType.SetArcDirection,
    EmfSetMiterLimit = MetafileRecordType.SetMiterLimit,
    EmfBeginPath = MetafileRecordType.BeginPath,
    EmfEndPath = MetafileRecordType.EndPath,
    EmfCloseFigure = MetafileRecordType.CloseFigure,
    EmfFillPath = MetafileRecordType.FillPath,
    EmfStrokeAndFillPath = MetafileRecordType.StrokeAndFillPath,
    EmfStrokePath = MetafileRecordType.StrokePath,
    EmfFlattenPath = MetafileRecordType.FlattenPath,
    EmfWidenPath = MetafileRecordType.WidenPath,
    EmfSelectClipPath = MetafileRecordType.SelectClipPath,
    EmfAbortPath = MetafileRecordType.AbortPath,
    EmfGdiComment = MetafileRecordType.GdiComment,
    EmfFillRgn = MetafileRecordType.FillRgn,
    EmfFrameRgn = MetafileRecordType.FrameRgn,
    EmfInvertRgn = MetafileRecordType.InvertRgn,
    EmfPaintRgn = MetafileRecordType.PaintRgn,
    EmfExtSelectClipRgn = MetafileRecordType.ExtSelectClipRgn,
    EmfBitBlt = MetafileRecordType.BitBlt,
    EmfStretchBlt = MetafileRecordType.StretchBlt,
    EmfMaskBlt = MetafileRecordType.MaskBlt,
    EmfPlgBlt = MetafileRecordType.PlgBlt,
    EmfSetDIBitsToDevice = MetafileRecordType.SetDIBitsToDevice,
    EmfStretchDIBits = MetafileRecordType.StretchDIBits,
    EmfExtCreateFontIndirectW = MetafileRecordType.ExtCreateFontIndirectW,
    EmfExtTextOutA = MetafileRecordType.ExtTextOutA,
    EmfExtTextOutW = MetafileRecordType.ExtTextOutW,
    EmfPolyBezier16 = MetafileRecordType.PolyBezier16,
    EmfPolygon16 = MetafileRecordType.Polygon16,
    EmfPolyline16 = MetafileRecordType.Polyline16,
    EmfPolyBezierTo16 = MetafileRecordType.PolyBezierTo16,
    EmfPolylineTo16 = MetafileRecordType.PolylineTo16,
    EmfPolyPolyline16 = MetafileRecordType.PolyPolyline16,
    EmfPolyPolygon16 = MetafileRecordType.PolyPolygon16,
    EmfPolyDraw16 = MetafileRecordType.PolyDraw16,
    EmfCreateMonoBrush = MetafileRecordType.CreateMonoBrush,
    EmfCreateDIBPatternBrushPt = MetafileRecordType.CreateDIBPatternBrushPt,
    EmfExtCreatePen = MetafileRecordType.ExtCreatePen,
    EmfPolyTextOutA = MetafileRecordType.PolyTextOutA,
    EmfPolyTextOutW = MetafileRecordType.PolyTextOutW,
    EmfSetICMMode = MetafileRecordType.SetICMMode,
    EmfCreatecolorspace = MetafileRecordType.Createcolorspace,
    EmfSetColorSpace = MetafileRecordType.SetColorSpace,
    EmfDeleteColorSpace = MetafileRecordType.DeleteColorSpace,
    EmfGLSRecord = MetafileRecordType.GLSRecord,
    EmfGLSBoundedRecord = MetafileRecordType.GLSBoundedRecord,
    EmfPixelFormat = MetafileRecordType.PixelFormat,
    EmfColorCorrectPalette = MetafileRecordType.ColorCorrectPalette,
    EmfSetICMProfileA = MetafileRecordType.SetICMProfileA,
    EmfSetICMProfileW = MetafileRecordType.SetICMProfileW,
    EmfAlphaBlend = MetafileRecordType.AlphaBlend,
    EmfSetLayout = MetafileRecordType.SetLayout,
    EmfTransparentBlt = MetafileRecordType.TransparentBlt,
    EmfGradientFill = MetafileRecordType.GradientFill,
    EmfColorMatchToTargetW = MetafileRecordType.ColorMatchToTargetW,
    EmfCreateColorSpaceW = MetafileRecordType.CreateColorSpaceW,

    EmfPlusInvalid = 0x4000,
    EmfPlusHeader,
    EmfPlusEndOfFile,
    EmfPlusComment,
    EmfPlusGetDC,
    EmfPlusMultiFormatStart,
    EmfPlusMultiFormatSection,
    EmfPlusMultiFormatEnd,
    EmfPlusObject,
    EmfPlusClear,
    EmfPlusFillRects,
    EmfPlusDrawRects,
    EmfPlusFillPolygon,
    EmfPlusDrawLines,
    EmfPlusFillEllipse,
    EmfPlusDrawEllipse,
    EmfPlusFillPie,
    EmfPlusDrawPie,
    EmfPlusDrawArc,
    EmfPlusFillRegion,
    EmfPlusFillPath,
    EmfPlusDrawPath,
    EmfPlusFillClosedCurve,
    EmfPlusDrawClosedCurve,
    EmfPlusDrawCurve,
    EmfPlusDrawBeziers,
    EmfPlusDrawImage,
    EmfPlusDrawImagePoints,
    EmfPlusDrawString,
    EmfPlusSetRenderingOrigin,
    EmfPlusSetAntiAliasMode,
    EmfPlusSetTextRenderingHint,
    EmfPlusSetTextContrast,
    EmfPlusSetInterpolationMode,
    EmfPlusSetPixelOffsetMode,
    EmfPlusSetCompositingMode,
    EmfPlusSetCompositingQuality,
    EmfPlusSave,
    EmfPlusRestore,
    EmfPlusBeginContainer,
    EmfPlusBeginContainerNoParams,
    EmfPlusEndContainer,
    EmfPlusSetWorldTransform,
    EmfPlusResetWorldTransform,
    EmfPlusMultiplyWorldTransform,
    EmfPlusTranslateWorldTransform,
    EmfPlusScaleWorldTransform,
    EmfPlusRotateWorldTransform,
    EmfPlusSetPageTransform,
    EmfPlusResetClip,
    EmfPlusSetClipRect,
    EmfPlusSetClipPath,
    EmfPlusSetClipRegion,
    EmfPlusOffsetClip,
    EmfPlusDrawDriverString,

    // These were added in GDI+ 1.1
    EmfPlusStrokeFillPath,
    EmfPlusSerializableObject,
    EmfPlusSetTSGraphics,
    EmfPlusSetTSClip,
}
