// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// (This file was generated by the T4 template engine)

namespace WInterop
{
    /// <summary>
    /// Auto generated constants
    /// </summary>
    internal static class AutoGeneratedConstants
    {
        public static class Integers
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const int CurrentYear = 2020;

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const int CurrentMonth = 8;

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const int CurrentDayOfMonth = 31;

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const int CurrentHour = 19;

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const int CurrentMinute = 7;
        }

        public static class Strings
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const string CurrentYear = "2020";

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const string CurrentMonth = "8";

            /// <summary>
            /// Current month 01..12
            /// </summary>
            public const string CurrentTwoDigitMonth = "08";

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const string CurrentDayOfMonth = "31";

            /// <summary>
            /// Current two digit day of the month 01..31
            /// </summary>
            public const string CurrentTwoDigitDayOfMonth = "31";

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const string CurrentHour = "19";

            /// <summary>
            /// Current two digit hour from 00..23
            /// </summary>
            public const string CurrentTwoDigitHour = "19";

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const string CurrentMinute = "7";

            /// <summary>
            /// Current two digit hour from 00..59
            /// </summary>
            public const string CurrentTwoDigitMinute = "07";
        }
    }
}
