// ------------------------
//    WInterop Framework
// ------------------------

// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// (This file was generated by the T4 template engine)

namespace WInterop
{
    /// <summary>
    /// Auto generated constants
    /// </summary>
    internal static class AutoGeneratedConstants
    {
        public static class Integers
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const int CurrentYear =  2017;

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const int CurrentMonth = 3;

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const int CurrentDayOfMonth =  10;

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const int CurrentHour = 21;

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const int CurrentMinute = 28;
        }

        public static class Strings
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const string CurrentYear =  "2017";

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const string CurrentMonth = "3";

            /// <summary>
            /// Current month 01..12
            /// </summary>
            public const string CurrentTwoDigitMonth = "03";

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const string CurrentDayOfMonth =  "10";

            /// <summary>
            /// Current two digit day of the month 01..31
            /// </summary>
            public const string CurrentTwoDigitDayOfMonth =  "10";

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const string CurrentHour = "21";

            /// <summary>
            /// Current two digit hour from 00..23
            /// </summary>
            public const string CurrentTwoDigitHour = "21";

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const string CurrentMinute = "28";

            /// <summary>
            /// Current two digit hour from 00..59
            /// </summary>
            public const string CurrentTwoDigitMinute = "28";
        }
    }
}
