<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.7.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WInterop.Desktop\WInterop.Desktop.csproj" />
    <ProjectReference Include="..\..\WInterop.DirectX\WInterop.Direct2d.csproj" />
    <ProjectReference Include="..\..\WInterop.GdiPlus\WInterop.GdiPlus.csproj" />
    <ProjectReference Include="..\..\WInterop.SourceGenerators\WInterop.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <!--
      Adding a project ref like this gets build order correct and copies the native dll to the output
      directory. The reference still gets a warning in the solution explorer, haven't dug in to find
      a way to prevent that.
    -->
    <ProjectReference Include="..\NativeTestLibrary\NativeTestLibrary.vcxproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Content</OutputItemType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
